apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: container-mysql
      image: mysql:5.7.24
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: "rentacar"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"